[options]
  # Look and Feel
  colorscheme = "onedark"
  colorscheme_bg = "dark"
  enable_guicolors = true
  default_indent = 4

  buffer_index_type = 4
  windows_index_type = 3

  statusline_separator = "arrow"
  statusline_iseparator = "bar"
  enable_statusline_mode = true
  statusline_left_sections = [
    "winnr",
    "filename",
    "major mode",
    "version control info"
  ]
  statusline_right_sections = [
    "cursorpos",
    "percentage"
  ]
  statusline_unicode_symbols = true

  # Editor config
  simple_mode = true
  autocomplete_method = "coc"
  filemanager = "defx"

  disabled_plugins = ["vim-import-js"]

# Util layers
[[layers]]
  name = "autocomplete"
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "cycle"

[[layers]]
  name = "shell"
  default_position = "top"
  default_height = 40

[[layers]]
  name = "ui"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "fzf"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "git"

[[layers]]
  name = "lsp"
  filetypes = [
    "typescript",
    "javascript",
    "vue",
  ]

# Language layers
[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#typescript"

